/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hedera.cli;

import org.junit.Test;

public class ApplicationTest {
    @Test 
    public void testApplication() {
    }
}
