/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hedera.cli;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class ApplicationTest {
    @Test
    public void testApplication() {
        assertTrue(true);
    }
}
