/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hedera.cli;
import org.joda.time.LocalTime;

public class App {

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        LocalTime currentTime = new LocalTime();
        System.out.println("The current local time is: " + currentTime);
    }
    public String getGreeting() {
        return "Hello world.";
    }
}
