/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hedera.cli;
import org.jline.utils.AttributedString;
import org.jline.utils.AttributedStyle;
import org.joda.time.LocalTime;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.shell.jline.PromptProvider;
import org.springframework.shell.standard.ShellComponent;
import org.springframework.shell.standard.ShellMethod;
import org.springframework.shell.standard.ShellOption;

@SpringBootApplication
public class HederaShell {

    public static void main(String[] args) throws Exception {
        ConfigurableApplicationContext context = SpringApplication.run(HederaShell.class, args);
    }

    // Use @ShellComponent in a separate class, tying ShellHelper Injection with @Autowire for more
    // modularized code vs @Bean in current file
//    @Bean
//    public PromptProvider CliPromptProvider() {
//        return () -> new AttributedString("Hedera:>", AttributedStyle.DEFAULT.foreground(AttributedStyle.YELLOW));
//    }

}




//@ShellComponent
//public class App {
//
//    private final String[] args;
//
//    @Autowired
//    public App(String[] args) {
//        this.args = args;
//    }
////    public static void main(@ShellOption() String[] args) {
////        System.out.println(new App(args).getGreeting());
////        LocalTime currentTime = new LocalTime();
////        System.out.println("The current local time is: " + currentTime);
////    }
//
//    @ShellMethod("get the greeting")
//    public String getGreeting(@ShellOption() String[] args) {
//        System.out.println(new App(args).getGreeting(args));
//        LocalTime currentTime = new LocalTime();
//        System.out.println("The current local time is: " + currentTime);
//        return "The current local time is: " + currentTime + "Hello." + args[0];
//    }
//}
