/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hedera.cli;

import java.io.File;
import java.util.List;

import com.hedera.cli.hedera.Hedera;
import com.hedera.cli.hedera.utils.DataDirectory;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@EnableAutoConfiguration
@ComponentScan("com.hedera.cli")
public class Application {

    public static void main(String[] args) {
        ApplicationContext context = SpringApplication.run(Application.class, args);
        // set defaults
        DataDirectory dataDirectory = new DataDirectory();
        dataDirectory.readFile("network.txt", "aspen");
        Hedera hedera = new Hedera(context);
        List<String> networkList = hedera.getNetworksStrings();
        for (String network: networkList) {
            String accountsDirForNetwork = network + File.separator + "accounts";
            dataDirectory.mkHederaSubDir(accountsDirForNetwork);
        }

        // Application app = new Application();
        // app.run

        // let Spring instantiate and inject dependencies
        // System.exit(SpringApplication.exit(SpringApplication.run(Application.class, args)));
    }
}