/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hedera.cli;

import org.junit.Test;
import static org.junit.Assert.*;

public class HederaShellTest {
    @Test public void testHederaShellHasAGreeting() {
        HederaShell classUnderTest = new HederaShell();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
