export default {
  network: 'testnet',
  mirrorNodeLocalnet: 'http://localhost:5551/api/v1',
  mirrorNodePreviewnet: 'https://previewnet.mirrornode.hedera.com/api/v1',
  mirrorNodeTestnet: 'https://testnet.mirrornode.hedera.com/api/v1',
  mirrorNodeMainnet: 'https://mainnet.mirrornode.hedera.com/api/v1',
  recording: 0,
  recordingScriptName: '',
  scriptExecution: 0,
  scriptExecutionName: '',
  accounts: {},
  tokens: {},
  scripts: {},
  topics: {},
  previewnetOperatorId: '',
  previewnetOperatorKey: '',
  testnetOperatorKey: '',
  testnetOperatorId: '',
  mainnetOperatorKey: '',
  mainnetOperatorId: '',
  localnetOperatorKey: '',
  localnetOperatorId: '',
  localNodeAddress: '127.0.0.1:50211',
  localNodeAccountId: '0.0.3',
  localNodeMirrorAddressGRPC: '127.0.0.1:5600',
};
