#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "husky - pre-push running tests"
npm run test:all
status=$?
if [ $status -ne 0 ]; then
	echo "husky - pre-push failed (code $status)"
	exit $status
fi
echo "husky - pre-push passed"
